Separate bacnet Ip connection and Serial connection.
IOT-DSA/dslink-java-bacnet pull request #17
Opened 2016-11-15 01:15 UTC by hhou2011

@Pacane

2016-11-15 22:53 UTC, Pacane requested changes

2016-11-15 22:53 UTC, Pacane commented on src/main/java/bacnet/BacnetConn.java
> +	abstract BacnetConn getBacnetConnection(BacnetLink link2, Node newnode);
link2?

2016-11-15 22:53 UTC, Pacane commented on src/main/java/bacnet/BacnetConn.java
>  			long interval = (long) (1000
could be named `intervalInMilliseconds` or something like that.

2016-11-15 22:53 UTC, Pacane commented on src/main/java/bacnet/BacnetConn.java
> +	void registerAsFeignDevice(Network newwork) {
network

2016-11-15 22:53 UTC, Pacane commented on src/main/java/bacnet/BacnetConn.java
>  	// public DeviceEventListener getListener() {
remove this if it's not useful

2016-11-15 22:53 UTC, Pacane commented on src/main/java/bacnet/BacnetIpConnection.java
> +	private void parseBBMD(String bbmdIpList) {
what is BBMD? What's the acronym for?

2016-11-15 22:53 UTC, Pacane commented on src/main/java/bacnet/BacnetIpConnection.java
> +	private void parseBBMD(String bbmdIpList) {
- Isn't there already something to parse IP addresses?

2016-11-15 22:53 UTC, Pacane commented on src/main/java/bacnet/BacnetIpConnection.java
> +	private void parseBBMD(String bbmdIpList) {
Maybe something like this http://stackoverflow.com/questions/2345063/java-common-way-to-validate-and-convert-hostport-to-inetsocketaddress

2016-11-15 22:53 UTC, Pacane commented on src/main/java/bacnet/BacnetIpConnection.java
> +						.registerAsForeignDevice(new InetSocketAddress(InetAddress.getByName(bbmdIp), bbmdPort), 100);
magic number

2016-11-15 22:55 UTC, hhou2011 commented on src/main/java/bacnet/BacnetConn.java
> +	abstract BacnetConn getBacnetConnection(BacnetLink link2, Node newnode);
Typo.

2016-11-15 23:13 UTC, hhou2011 commented on src/main/java/bacnet/BacnetIpConnection.java
> +	private void parseBBMD(String bbmdIpList) {
bbmd = broadcast management device. Usually the short name is used in the bacnet protocol.

2016-11-16 00:06 UTC, hhou2011 commented on src/main/java/bacnet/BacnetIpConnection.java
> +	private void parseBBMD(String bbmdIpList) {
Yes, I use pattern now.

2016-11-16 01:48 UTC, Pacane approved these changes

2016-11-16 19:12 UTC, merged