update to sdk version 0.17.1
IOT-DSA/dslink-java-bacnet pull request #23
Opened 2017-02-13 20:09 UTC by d-shapiro

2017-02-13 22:26 UTC, Pacane requested changes

2017-02-13 22:26 UTC, Pacane commented on src/main/java/bacnet/BacnetPoint.java
>  		// if (DeviceFolder.isOneOf(oid.getObjectType(), ObjectType.trendLog)) {
remove if unused.

2017-02-13 22:26 UTC, Pacane commented on src/main/java/bacnet/DeviceFolder.java
> +		parentobj.put(org.dsa.iot.dslink.util.StringUtils.encodeName(name), nodeobj);
Any reason for the full name here?

2017-02-13 22:26 UTC, Pacane commented on src/main/java/bacnet/LocalDeviceNode.java
>  					// enable(true);
remove if unused

2017-02-14 00:07 UTC, d-shapiro commented on src/main/java/bacnet/DeviceFolder.java
> +		parentobj.put(org.dsa.iot.dslink.util.StringUtils.encodeName(name), nodeobj);
org.apache.commons.lang3.StringUtils

2017-02-16 18:24 UTC, hhou2011 approved these changes

2017-02-16 19:29 UTC, merged